global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:8080', 'auth_service:9090']

  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:8080', 'user_service:9090']

  - job_name: 'driver_service'
    static_configs:
      - targets: ['driver_service:8080', 'driver_service:9090']

  - job_name: 'wallet_service'
    static_configs:
      - targets: ['wallet_service:8080', 'wallet_service:9090']

  - job_name: 'order_service'
    static_configs:
      - targets: ['order_service:8080', 'order_service:9090']
